# Generated by Django 3.0.8 on 2020-08-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=11)),
                ('pubDate', models.DateTimeField(auto_now=True)),
                ('viewsCount', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
